# Generated by Django 4.1.2 on 2022-11-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='expiresAt',
        ),
    ]
