# Generated by Django 4.1.2 on 2022-11-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_externalnode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalnode',
            old_name='url',
            new_name='host',
        ),
        migrations.AddField(
            model_name='externalnode',
            name='api',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
