# Generated by Django 4.1.2 on 2022-10-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('host', models.URLField()),
                ('displayName', models.CharField(max_length=255)),
                ('github', models.URLField()),
                ('profileImage', models.URLField()),
            ],
        ),
    ]
