# Generated by Django 4.1.2 on 2022-10-22 03:36

# authors/migrations/0002_follower_isaccepted_alter_author_host_and_more.py
#     - Add field isAccepted to follower
#     - Alter field host on author
#     - Alter field id on author
#     - Alter field type on author
#     - Alter unique_together for follower (1 constraint(s))

import authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=authors.models.get_scheme_and_netloc, editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=authors.models.generate_random_string, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', editable=False, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('author', 'follower')},
        ),
    ]
