# Generated by Django 4.1.2 on 2022-11-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_profileimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.TextField(),
        ),
    ]
