# Generated by Django 4.1.2 on 2022-11-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_remove_post_count_post_unlisted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(),
        ),
    ]
