# Generated by Django 4.1.2 on 2022-11-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_remove_author_followers_remove_follower_isaccepted'),
        ('posts', '0003_prep_for_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='authors.author'),
        ),
    ]
