# Generated by Django 4.1.2 on 2022-11-24 10:28

from django.db import migrations, models
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default=utils.model_utils.generate_random_string, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
