# Generated by Django 4.1.2 on 2022-11-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visibilty',
            new_name='visibility',
        ),
    ]
